const baseItems = {
    granum: "Granum", calx: "Calx", saburra: "Saburra", tephra: "Tephra",
    sp: "Saburra Powder", cp: "Calx Powder",
    bo: "Blood Ore", gs: "Grain Steel",
    cuprum: "Cuprum", bron: "Bron", messing: "Messing", tmessing: "Tindremic Messing", tungsteel: "Tungsteel", cronite: "Cronite", oghmium: "Oghmium",
    amarantum: "Amarantum", flakestone: "Flakestone", granumpowder: "Granum Powder", malachite: "Malachite", bleckblende: "Bleckblende", calamine: "Calamine",
    jadeite: "Jadeite", calspar: "Calspar", galbinum: "Galbinum", redbleckblende: "Red Bleckblende", pyroxene: "Pyroxene", almine: "Almine", acronite: "Acronite",
    sanguinite: "Sanguinite", fumingsalt: "Fuming Salt", lupium: "Lupium", gemmetal: "Gem Metal"
};

const i18n = {
    en: {
        tabPrefs: "Preferences", tabInteg: "Integrations", tabData: "Data", tabHelp: "Help", resetDesc: "Clear all your saved bank inventory, market cart quantities, and targets.",
        shareTitle: "Share / Import Setup", shareDesc: "Generate a code to share your current bank, market cart, and target with others, or paste a code to load theirs.",
        btnGenCode: "📤 Generate & Copy", btnLoadCode: "📥 Load Code", importSuccess: "Setup loaded successfully!", importError: "Invalid code provided.", exportSuccess: "Code copied to clipboard!",
        themeToggle: "☀️ / 🌙 Toggle Day/Night Mode", format: "Display Format", optUnits: "Units", optStacks: "Stacks (10k)", webhook: "Discord Webhook URL",
        prodCmd: "Production Command", targetMetalLabel: "Target Metal", boSource: "Extraction Strategy", optAttractor: "Efficient (Grinders)", optCrusher: "Max Yield (Crushers)", crafters: "Crafters", target: "Amount", 
        btnMaxText: "⚡ Calculate Craftable From Inventory",
        yieldMods: "Yield Modifiers", mastery: "Mastery (+6%)", refining: "Refining (+3%)", extraction: "Extraction (+3%)",
        btnDiscord: "📋 Copy to Clipboard", btnSend: "🚀 Send Order to Discord",
        invBank: "Inventory Bank", showAllBank: "Show All Materials", btnReset: "🧹 Reset All Bank & Cart", defGather: "Deficit to Gather Manually", mfgPipe: "Manufacturing Pipeline", marketCart: "Market Cart", btnAutoFill: "🛒 Auto-Fill All",
        tblPrice: "Price/10k", tblBuy: "Amount to Buy", tblCost: "Cost (g)", tblStash: "Bank + Buy", cartTotal: "Cart Total:",
        noTarget: "No target set.", allCovered: "✅ Bank & Cart cover all raw materials!",
        stepYields: "yields", stepExtract: "Extract", stepAnd: "and", perCrafter: "(Per Crafter)", stepPrefix: "Step",
        resetPrompt: "Reset all bank values and shopping cart to zero?", discHeader: "⚔️ LOGISTICS ORDER", discReq: "MANUAL GATHER REQUIRED:", discStock: "All gathering covered.", discCopied: "Copied to clipboard!",
        discMarket: "MARKET PURCHASES:", errWebhook: "Please enter a valid Discord Webhook URL.", errSend: "Failed to send to Discord.", sucSend: "Order dispatched to Discord!",
        qAdd: "+10k", qAddStk: "+1 Stk", byproductsTitle: "RECOVERED BYPRODUCTS",
        categories: { raw: "Raw Materials", basicExt: "Basic Extractions", intOre: "Intermediate Ores", advOre: "Advanced Ores", catalyst: "Catalysts", refined: "Refined Metals" },
        items: { ...baseItems, water: "Water", coal: "Coal", coke: "Coke", steel: "Steel", pi: "Pig Iron" },
        
        helpSubtitle: "The ultimate MO2 manufacturing calculator and logistics dashboard.",
        helpFeatures: "🌟 Feature Overview",
        helpFeat1: "<b>Pipeline Intelligence:</b> Automatically maps out multi-step extraction, refining, and smelting tasks. Skips steps if you already have intermediate materials (like Pig Iron) in your bank.",
        helpFeat2: "<b>Calculate Craftable:</b> Scans your current bank inventory to calculate the absolute maximum amount of target metal you can produce with what you have.",
        helpFeat3: "<b>Smart Market Cart:</b> Enter market prices and buy quantities. Use <i>Auto-Fill All</i> to calculate exactly how much you need to buy and see the <b>Total Gold Cost</b>.",
        helpFeat4: "<b>Share / Import:</b> Generate a Base64 code of your current setup to instantly share with guildmates or transfer between devices.",
        helpFeat5: "<b>Discord Dispatch:</b> Generates a beautifully formatted Markdown work order—separating Market Purchases from Manual Gathering—ready to paste directly into Discord.",
        helpHowTo: "📖 How to Use",
        helpHow1: "<b>Set Your Objective:</b> Select your <i>Target Metal</i> (e.g., Steel) and desired <i>Amount</i>. Set your <i>Crafters</i> count to automatically divide the workload.",
        helpHow2: "<b>Check Your Bank:</b> Input your current inventory into the <i>Inventory Bank</i>. <br><i>Tip: If you don't know what to make, enter your materials and click <b>⚡ Calculate Craftable From Inventory</b> to see your limits.</i>",
        helpHow3: "<b>Go Shopping:</b> Check the <i>Market Cart</i> module. Set local prices, then click <b>🛒 Auto-Fill All</b> to calculate your missing deficit and required gold budget.",
        helpHow4: "<b>Dispatch the Order:</b> Review the <i>Deficit to Gather</i> and <i>Manufacturing Pipeline</i>. Go to Settings > Integrations and copy the order to your clipboard for Discord."
    },
    
    fr: {
        tabPrefs: "Préférences", tabInteg: "Intégrations", tabData: "Données", tabHelp: "Aide", resetDesc: "Effacez tout votre inventaire, les quantités du panier et les objectifs.",
        shareTitle: "Partager / Importer", shareDesc: "Générez un code pour partager votre banque, panier et objectif, ou collez un code pour charger celui d'un autre joueur.",
        btnGenCode: "📤 Générer & Copier", btnLoadCode: "📥 Charger", importSuccess: "Configuration chargée avec succès !", importError: "Code invalide.", exportSuccess: "Code copié dans le presse-papiers !",
        themeToggle: "☀️ / 🌙 Mode Jour/Nuit", format: "Format d'affichage", optUnits: "Unités", optStacks: "Piles (10k)", webhook: "URL Webhook Discord",
        prodCmd: "Commande de Production", targetMetalLabel: "Métal Cible", boSource: "Stratégie d'Extraction", optAttractor: "Efficace (Broyeurs)", optCrusher: "Rendement Max (Concasseurs)", crafters: "Artisans", target: "Quantité", 
        btnMaxText: "⚡ Calculer la production possible",
        yieldMods: "Modificateurs", mastery: "Maîtrise (+6%)", refining: "Raffinage (+3%)", extraction: "Extraction (+3%)",
        btnDiscord: "📋 Copier l'ordre", btnSend: "🚀 Envoyer sur Discord",
        invBank: "Banque d'Inventaire", showAllBank: "Afficher Tout", btnReset: "🧹 Réinitialiser Tout", defGather: "Déficit à Récolter", mfgPipe: "Pipeline de Fabrication", marketCart: "Panier", btnAutoFill: "🛒 Tout Remplir",
        tblPrice: "Prix/10k", tblBuy: "Qté à Acheter", tblCost: "Coût (o)", tblStash: "Banque + Achat", cartTotal: "Total Panier :",
        noTarget: "Aucun objectif défini.", allCovered: "✅ La banque couvre tout !",
        stepYields: "produit", stepExtract: "Extraire", stepAnd: "et", perCrafter: "(Par Artisan)", stepPrefix: "Étape",
        resetPrompt: "Réinitialiser toutes les valeurs à zéro ?", discHeader: "⚔️ ORDRE LOGISTIQUE", discReq: "RÉCOLTE MANUELLE REQUISE :", discStock: "Toute la récolte est couverte.", discCopied: "Copié dans le presse-papiers !",
        discMarket: "ACHATS AU MARCHÉ :", errWebhook: "URL Webhook invalide.", errSend: "Échec de l'envoi.", sucSend: "Ordre envoyé sur Discord !",
        qAdd: "+10k", qAddStk: "+1 Pile", byproductsTitle: "SOUS-PRODUITS RÉCUPÉRÉS",
        categories: { raw: "Matières Premières", basicExt: "Extractions de Base", intOre: "Minerais Intermédiaires", advOre: "Minerais Avancés", catalyst: "Catalyseurs", refined: "Métaux Raffinés" },
        items: { ...baseItems, water: "Eau", coal: "Charbon", coke: "Coke", steel: "Acier", pi: "Fonte (Pig Iron)" },
        
        helpSubtitle: "L'ultime calculateur de fabrication et tableau de bord logistique pour MO2.",
        helpFeatures: "🌟 Aperçu des Fonctionnalités",
        helpFeat1: "<b>Intelligence du Pipeline :</b> Cartographie automatiquement les étapes d'extraction, de raffinage et de fusion. Ignore les étapes si vous possédez déjà des matériaux intermédiaires (comme la Fonte) en banque.",
        helpFeat2: "<b>Calculer la Production Possible :</b> Analyse votre inventaire bancaire actuel pour calculer la quantité maximale absolue du métal ciblé que vous pouvez produire avec ce que vous avez.",
        helpFeat3: "<b>Panier Intelligent :</b> Entrez les prix du marché et les quantités d'achat. Utilisez <i>Tout Remplir</i> pour calculer exactement combien vous devez acheter et voir le <b>Coût Total en Or</b>.",
        helpFeat4: "<b>Partager / Importer :</b> Générez un code Base64 de votre configuration actuelle pour la partager instantanément avec vos camarades de guilde ou la transférer entre vos appareils.",
        helpFeat5: "<b>Envoi Discord :</b> Génère un ordre de travail Markdown magnifiquement formaté, séparant les achats au marché de la récolte manuelle, prêt à être collé directement dans Discord.",
        helpHowTo: "📖 Comment utiliser",
        helpHow1: "<b>Définissez votre Objectif :</b> Sélectionnez votre <i>Métal Cible</i> (ex. Acier) et la <i>Quantité</i> désirée. Définissez le nombre d'<i>Artisans</i> pour diviser automatiquement la charge de travail.",
        helpHow2: "<b>Vérifiez votre Banque :</b> Entrez votre inventaire actuel dans la <i>Banque d'Inventaire</i>. <br><i>Astuce : Si vous ne savez pas quoi fabriquer, entrez vos matériaux et cliquez sur <b>⚡ Calculer la production possible</b> pour voir vos limites.</i>",
        helpHow3: "<b>Faites vos Achats :</b> Consultez le module <i>Panier</i>. Définissez les prix locaux, puis cliquez sur <b>🛒 Tout Remplir</b> pour calculer votre déficit manquant et votre budget en or requis.",
        helpHow4: "<b>Envoyez l'Ordre :</b> Passez en revue le <i>Déficit à Récolter</i> et le <i>Pipeline de Fabrication</i>. Allez dans Paramètres > Intégrations et copiez l'ordre dans votre presse-papiers pour Discord."
    },
    
    es: {
        tabPrefs: "Preferencias", tabInteg: "Integraciones", tabData: "Datos", tabHelp: "Ayuda", resetDesc: "Borra todo tu inventario, cantidades del carrito y objetivos.",
        shareTitle: "Compartir / Importar", shareDesc: "Genera un código para compartir tu banco, carrito y objetivo con otros, o pega un código para cargar el de ellos.",
        btnGenCode: "📤 Generar y Copiar", btnLoadCode: "📥 Cargar Código", importSuccess: "¡Configuración cargada con éxito!", importError: "Código inválido.", exportSuccess: "¡Código copiado al portapapeles!",
        themeToggle: "☀️ / 🌙 Modo Día/Noche", format: "Formato", optUnits: "Unidades", optStacks: "Pilas (10k)", webhook: "URL Webhook de Discord",
        prodCmd: "Comando de Producción", targetMetalLabel: "Metal Objetivo", boSource: "Estrategia", optAttractor: "Eficiente (Molinillos)", optCrusher: "Rendimiento Max (Trituradoras)", crafters: "Artesanos", target: "Cantidad", 
        btnMaxText: "⚡ Calcular producción posible",
        yieldMods: "Modificadores", mastery: "Maestría (+6%)", refining: "Refinación (+3%)", extraction: "Extracción (+3%)",
        btnDiscord: "📋 Copiar al Portapapeles", btnSend: "🚀 Enviar a Discord",
        invBank: "Banco de Inventario", showAllBank: "Mostrar Todo", btnReset: "🧹 Restablecer Todo", defGather: "Déficit a Recolectar", mfgPipe: "Tubería de Fabricación", marketCart: "Carrito de Mercado", btnAutoFill: "🛒 Llenar Todo",
        tblPrice: "Precio/10k", tblBuy: "Cant. a Comprar", tblCost: "Costo (o)", tblStash: "Banco + Compra", cartTotal: "Total Carrito:",
        noTarget: "Sin objetivo.", allCovered: "✅ ¡Todo cubierto!",
        stepYields: "produce", stepExtract: "Extraer", stepAnd: "y", perCrafter: "(Por Artesano)", stepPrefix: "Paso",
        resetPrompt: "¿Restablecer todos los valores a cero?", discHeader: "⚔️ ORDEN LOGÍSTICA", discReq: "RECOLECCIÓN MANUAL:", discStock: "Toda la recolección cubierta.", discCopied: "¡Copiado!",
        discMarket: "COMPRAS EN MERCADO:", errWebhook: "URL Webhook inválida.", errSend: "Error al enviar.", sucSend: "¡Orden enviada!",
        qAdd: "+10k", qAddStk: "+1 Pila", byproductsTitle: "SUBPRODUCTOS RECUPERADOS",
        categories: { raw: "Materias Primas", basicExt: "Extracciones Básicas", intOre: "Minerales Intermedios", advOre: "Minerales Avanzados", catalyst: "Catalizadores", refined: "Metales Refinados" },
        items: { ...baseItems, water: "Agua", coal: "Carbón", coke: "Coque", steel: "Acero", pi: "Arrabio" },
        helpSubtitle: "La calculadora de fabricación y panel logístico definitivo para MO2.",
        helpFeatures: "🌟 Resumen de Funciones",
        helpFeat1: "<b>Inteligencia de Producción:</b> Planifica automáticamente los pasos de extracción, refinamiento y fundición. Omite pasos si ya tienes materiales intermedios en el banco.",
        helpFeat2: "<b>Calcular Fabricable:</b> Escanea tu inventario del banco para calcular la cantidad máxima absoluta del metal objetivo que puedes producir con lo que tienes.",
        helpFeat3: "<b>Carrito Inteligente:</b> Ingresa precios del mercado y cantidades. Usa <i>Llenar Todo</i> para calcular exactamente cuánto necesitas comprar y ver el <b>Costo Total de Oro</b>.",
        helpFeat4: "<b>Compartir / Importar:</b> Genera un código de tu configuración actual para compartir al instante con compañeros de gremio o transferir entre dispositivos.",
        helpFeat5: "<b>Envío a Discord:</b> Genera una orden de trabajo en Markdown bellamente formateada, separando compras de mercado y recolección manual, lista para pegar en Discord.",
        helpHowTo: "📖 Cómo usar",
        helpHow1: "<b>Establece tu Objetivo:</b> Selecciona tu <i>Metal Objetivo</i> y la <i>Cantidad</i> deseada. Configura tus <i>Artesanos</i> para dividir la carga de trabajo.",
        helpHow2: "<b>Revisa tu Banco:</b> Ingresa tu inventario actual en el <i>Banco de Inventario</i>. <br><i>Consejo: Si no sabes qué hacer, ingresa tus materiales y haz clic en <b>⚡ Calcular producción posible</b>.</i>",
        helpHow3: "<b>Ve de Compras:</b> Revisa el <i>Carrito de Mercado</i>. Establece precios locales, luego haz clic en <b>🛒 Llenar Todo</b> para calcular tu déficit y oro necesario.",
        helpHow4: "<b>Despacha la Orden:</b> Revisa el <i>Déficit a Recolectar</i> y la <i>Tubería de Fabricación</i>. Ve a Configuración > Integraciones y copia la orden a tu portapapeles."
    },
    
    de: {
        tabPrefs: "Einstellungen", tabInteg: "Integrationen", tabData: "Daten", tabHelp: "Hilfe", resetDesc: "Löschen Sie Ihr gesamtes gespeichertes Inventar und den Warenkorb.",
        shareTitle: "Setup Teilen / Importieren", shareDesc: "Generiere einen Code, um deine aktuelle Bank, den Warenkorb und das Ziel zu teilen, oder füge einen Code ein, um ihn zu laden.",
        btnGenCode: "📤 Generieren & Kopieren", btnLoadCode: "📥 Code Laden", importSuccess: "Setup erfolgreich geladen!", importError: "Ungültiger Code angegeben.", exportSuccess: "Code in die Zwischenablage kopiert!",
        themeToggle: "☀️ / 🌙 Tag/Nacht-Modus", format: "Anzeigeformat", optUnits: "Einheiten", optStacks: "Stapel (10k)", webhook: "Discord Webhook URL",
        prodCmd: "Produktionskommando", targetMetalLabel: "Zielmetall", boSource: "Extraktionsstrategie", optAttractor: "Effizient (Schleifer)", optCrusher: "Maximaler Ertrag (Brecher)", crafters: "Handwerker", target: "Menge", 
        btnMaxText: "⚡ Berechne Herstellbares",
        yieldMods: "Ertragsmodifikatoren", mastery: "Meisterschaft (+6%)", refining: "Raffinieren (+3%)", extraction: "Extraktion (+3%)",
        btnDiscord: "📋 In die Zwischenablage kopieren", btnSend: "🚀 An Discord senden",
        invBank: "Bankinventar", showAllBank: "Alle Anzeigen", btnReset: "🧹 Alles Zurücksetzen", defGather: "Fehlbetrag Sammeln", mfgPipe: "Herstellungspipeline", marketCart: "Warenkorb", btnAutoFill: "🛒 Alle automatisch ausfüllen",
        tblPrice: "Preis/10k", tblBuy: "Kaufmenge", tblCost: "Kosten (g)", tblStash: "Bank + Kauf", cartTotal: "Warenkorb Gesamt:",
        noTarget: "Kein Ziel gesetzt.", allCovered: "✅ Alles abgedeckt!",
        stepYields: "ergibt", stepExtract: "Extrahieren", stepAnd: "und", perCrafter: "(Pro Handwerker)", stepPrefix: "Schritt",
        resetPrompt: "Alle Werte auf null zurücksetzen?", discHeader: "⚔️ LOGISTIK-BESTELLUNG", discReq: "MANUELLES SAMMELN ERFORDERLICH:", discStock: "Alles abgedeckt.", discCopied: "Kopiert!",
        discMarket: "MARKTKÄUFE:", errWebhook: "Ungültige Webhook URL.", errSend: "Senden fehlgeschlagen.", sucSend: "Bestellung gesendet!",
        qAdd: "+10k", qAddStk: "+1 Stapel", byproductsTitle: "RÜCKGEWONNENE NEBENPRODUKTE",
        categories: { raw: "Rohmaterialien", basicExt: "Basis-Extraktionen", intOre: "Mittlere Erze", advOre: "Fortgeschrittene Erze", catalyst: "Katalysatoren", refined: "Raffinierte Metalle" },
        items: { ...baseItems, water: "Wasser", coal: "Kohle", coke: "Koks", steel: "Stahl", pi: "Roheisen" },
        helpSubtitle: "Der ultimative MO2-Herstellungsrechner und Logistik-Dashboard.",
        helpFeatures: "🌟 Funktionsübersicht",
        helpFeat1: "<b>Pipeline-Intelligenz:</b> Plant automatisch mehrstufige Extraktions-, Raffinierungs- und Schmelzaufgaben. Überspringt Schritte, wenn Sie Zwischenmaterialien auf der Bank haben.",
        helpFeat2: "<b>Berechne Herstellbares:</b> Scannt Ihr Bankinventar, um die maximale Menge des Zielmetalls zu berechnen, die Sie mit Ihren Materialien herstellen können.",
        helpFeat3: "<b>Smarter Warenkorb:</b> Geben Sie Marktpreise und Kaufmengen ein. Nutzen Sie <i>Alle automatisch ausfüllen</i>, um zu sehen, wie viel Gold Sie benötigen.",
        helpFeat4: "<b>Setup Teilen / Importieren:</b> Generieren Sie einen Code Ihres Setups, um es sofort mit Gildenmitgliedern zu teilen oder zwischen Geräten zu übertragen.",
        helpFeat5: "<b>Discord-Versand:</b> Generiert einen schön formatierten Markdown-Arbeitsauftrag – getrennt nach Marktkäufen und manueller Sammlung – bereit für Discord.",
        helpHowTo: "📖 Anleitung",
        helpHow1: "<b>Ziel setzen:</b> Wählen Sie Ihr <i>Zielmetall</i> und die gewünschte <i>Menge</i>. Stellen Sie die Anzahl der <i>Handwerker</i> ein, um die Arbeit aufzuteilen.",
        helpHow2: "<b>Bank überprüfen:</b> Geben Sie Ihr aktuelles Inventar in das <i>Bankinventar</i> ein. <br><i>Tipp: Wenn Sie nicht wissen, was Sie herstellen sollen, klicken Sie auf <b>⚡ Berechne Herstellbares</b>.</i>",
        helpHow3: "<b>Einkaufen:</b> Überprüfen Sie den <i>Warenkorb</i>. Legen Sie lokale Preise fest und klicken Sie auf <b>🛒 Alle ausfüllen</b>, um das Defizit zu berechnen.",
        helpHow4: "<b>Auftrag erteilen:</b> Überprüfen Sie den <i>Fehlbetrag</i>. Gehen Sie zu Einstellungen > Integrationen und kopieren Sie den Auftrag für Discord in die Zwischenablage."
    },

    it: {
        tabPrefs: "Preferenze", tabInteg: "Integrazioni", tabData: "Dati", tabHelp: "Aiuto", resetDesc: "Cancella l'inventario, le quantità del carrello e gli obiettivi.",
        shareTitle: "Condividi / Importa", shareDesc: "Genera un codice per condividere la tua banca, il carrello e l'obiettivo, o incolla un codice per caricare quello di altri.",
        btnGenCode: "📤 Genera e Copia", btnLoadCode: "📥 Carica Codice", importSuccess: "Configurazione caricata con successo!", importError: "Codice fornito non valido.", exportSuccess: "Codice copiato negli appunti!",
        themeToggle: "☀️ / 🌙 Giorno/Notte", format: "Formato", optUnits: "Unità", optStacks: "Stack (10k)", webhook: "Discord Webhook URL",
        prodCmd: "Comando Produzione", targetMetalLabel: "Metallo Obiettivo", boSource: "Strategia", optAttractor: "Efficiente (Macinatori)", optCrusher: "Resa Max (Frantoi)", crafters: "Artigiani", target: "Quantità", 
        btnMaxText: "⚡ Calcola producibile",
        yieldMods: "Modificatori", mastery: "Maestria (+6%)", refining: "Raffinazione (+3%)", extraction: "Estrazione (+3%)",
        btnDiscord: "📋 Copia negli Appunti", btnSend: "🚀 Invia a Discord",
        invBank: "Banca Inventario", showAllBank: "Mostra Tutto", btnReset: "🧹 Ripristina Tutto", defGather: "Deficit da Raccogliere", mfgPipe: "Pipeline di Produzione", marketCart: "Carrello", btnAutoFill: "🛒 Riempi Tutto",
        tblPrice: "Prezzo/10k", tblBuy: "Q.tà da Comprare", tblCost: "Costo (o)", tblStash: "Banca + Compra", cartTotal: "Totale Carrello:",
        noTarget: "Nessun obiettivo.", allCovered: "✅ Tutto coperto!",
        stepYields: "produce", stepExtract: "Estrai", stepAnd: "e", perCrafter: "(Per Artigiano)", stepPrefix: "Passo",
        resetPrompt: "Ripristinare tutti i valori a zero?", discHeader: "⚔️ ORDINE LOGISTICO", discReq: "RACCOLTA MANUALE:", discStock: "Tutta la raccolta coperta.", discCopied: "Copiato!",
        discMarket: "ACQUISTI DI MERCATO:", errWebhook: "URL Webhook non valido.", errSend: "Errore di invio.", sucSend: "Ordine inviato!",
        qAdd: "+10k", qAddStk: "+1 Stack", byproductsTitle: "SOTTOPRODOTTI RECUPERATI",
        categories: { raw: "Materie Prime", basicExt: "Estrazioni di Base", intOre: "Minerali Intermedi", advOre: "Minerali Avanzati", catalyst: "Catalizzatori", refined: "Metalli Raffinati" },
        items: { ...baseItems, water: "Acqua", coal: "Carbone", coke: "Coke", steel: "Acciaio", pi: "Ghisa" },
        helpSubtitle: "Il calcolatore di produzione e pannello logistico definitivo per MO2.",
        helpFeatures: "🌟 Panoramica delle Funzioni",
        helpFeat1: "<b>Intelligenza della Pipeline:</b> Mappa automaticamente i passaggi di estrazione e fusione. Salta i passaggi se possiedi già materiali intermedi nella banca.",
        helpFeat2: "<b>Calcola Producibile:</b> Analizza il tuo inventario per calcolare la quantità massima assoluta del metallo bersaglio che puoi produrre.",
        helpFeat3: "<b>Carrello Intelligente:</b> Inserisci i prezzi di mercato. Usa <i>Riempi Tutto</i> per calcolare esattamente quanto comprare e vedere il <b>Costo Totale in Oro</b>.",
        helpFeat4: "<b>Condividi / Importa:</b> Genera un codice della tua configurazione per condividerla con i compagni di gilda o trasferirla tra dispositivi.",
        helpFeat5: "<b>Invio a Discord:</b> Genera un ordine di lavoro formattato in Markdown—separando acquisti e raccolta manuale—pronto da incollare su Discord.",
        helpHowTo: "📖 Come si Usa",
        helpHow1: "<b>Imposta l'Obiettivo:</b> Seleziona il tuo <i>Metallo Obiettivo</i> e la <i>Quantità</i>. Imposta il numero di <i>Artigiani</i> per dividere il carico di lavoro.",
        helpHow2: "<b>Controlla la Banca:</b> Inserisci il tuo inventario nella <i>Banca Inventario</i>. <br><i>Suggerimento: Clicca <b>⚡ Calcola producibile</b> per vedere i tuoi limiti di craft.</i>",
        helpHow3: "<b>Fai Acquisti:</b> Controlla il modulo <i>Carrello</i>. Imposta i prezzi locali, poi clicca <b>🛒 Riempi Tutto</b> per calcolare il deficit e il budget d'oro.",
        helpHow4: "<b>Spedisci l'Ordine:</b> Rivedi il <i>Deficit</i> e la <i>Pipeline</i>. Vai su Impostazioni > Integrazioni e copia l'ordine negli appunti per Discord."
    },

    ro: {
        tabPrefs: "Preferințe", tabInteg: "Integrări", tabData: "Date", tabHelp: "Ajutor", resetDesc: "Ștergeți inventarul băncii, coșul și obiectivele.",
        shareTitle: "Partajează / Importă", shareDesc: "Generează un cod pentru a partaja banca, coșul și obiectivul tău, sau lipește un cod pentru a încărca pe al altora.",
        btnGenCode: "📤 Generează & Copiază", btnLoadCode: "📥 Încarcă Codul", importSuccess: "Configurație încărcată cu succes!", importError: "Cod invalid furnizat.", exportSuccess: "Cod copiat în clipboard!",
        themeToggle: "☀️ / 🌙 Mod Zi/Noapte", format: "Format Afișare", optUnits: "Unități", optStacks: "Stive (10k)", webhook: "Discord Webhook URL",
        prodCmd: "Comandă Producție", targetMetalLabel: "Metal Țintă", boSource: "Strategie Extracție", optAttractor: "Eficient (Polizoare)", optCrusher: "Randament Max (Concasoare)", crafters: "Artizani", target: "Cantitate", 
        btnMaxText: "⚡ Calculează ce poți fabrica",
        yieldMods: "Modificatori", mastery: "Măiestrie (+6%)", refining: "Rafinare (+3%)", extraction: "Extracție (+3%)",
        btnDiscord: "📋 Copiază în Clipboard", btnSend: "🚀 Trimite la Discord",
        invBank: "Inventar Bancă", showAllBank: "Arată Tot", btnReset: "🧹 Resetează Tot", defGather: "Deficit de Adunat", mfgPipe: "Proces de Fabricație", marketCart: "Coș Piață", btnAutoFill: "🛒 Umple Tot",
        tblPrice: "Preț/10k", tblBuy: "Cant. de Cumpărat", tblCost: "Cost (a)", tblStash: "Bancă + Cumpărat", cartTotal: "Total Coș:",
        noTarget: "Fără țintă.", allCovered: "✅ Totul este acoperit!",
        stepYields: "produce", stepExtract: "Extrage", stepAnd: "și", perCrafter: "(Per Artizan)", stepPrefix: "Pas",
        resetPrompt: "Resetați toate valorile la zero?", discHeader: "⚔️ ORDIN LOGISTIC", discReq: "ADUNARE MANUALĂ NECESARĂ:", discStock: "Necesar acoperit.", discCopied: "Copiat!",
        discMarket: "CUMPĂRĂTURI PIAȚĂ:", errWebhook: "URL Webhook invalid.", errSend: "Eroare la trimitere.", sucSend: "Ordin trimis!",
        qAdd: "+10k", qAddStk: "+1 Stivă", byproductsTitle: "SUBPRODUSE RECUPERATE",
        categories: { raw: "Materii Prime", basicExt: "Extracții de Bază", intOre: "Minereuri Intermediare", advOre: "Minereuri Avansate", catalyst: "Catalizatori", refined: "Metale Rafinate" },
        items: { ...baseItems, water: "Apă", coal: "Cărbune", coke: "Cocs", steel: "Oțel", pi: "Fontă" },
        helpSubtitle: "Calculatorul suprem de producție și panou logistic pentru MO2.",
        helpFeatures: "🌟 Prezentare Funcții",
        helpFeat1: "<b>Inteligența Procesului:</b> Planifică automat pașii de extracție și rafinare. Omite pașii dacă aveți deja materiale intermediare în bancă.",
        helpFeat2: "<b>Calculează ce poți fabrica:</b> Scanează inventarul pentru a calcula cantitatea maximă absolută de metal pe care o poți produce.",
        helpFeat3: "<b>Coș Inteligent:</b> Introduceți prețurile pieței. Folosiți <i>Umple Tot</i> pentru a calcula exact cât aur vă trebuie.",
        helpFeat4: "<b>Partajare / Import:</b> Generați un cod al configurației pentru a partaja instantaneu cu membrii breslei.",
        helpFeat5: "<b>Expediere Discord:</b> Generează o comandă de lucru formatată Markdown—separând cumpărăturile de adunarea manuală—gata pentru Discord.",
        helpHowTo: "📖 Cum se Folosește",
        helpHow1: "<b>Setează Obiectivul:</b> Selectează <i>Metalul Țintă</i> și <i>Cantitatea</i>. Setează numărul de <i>Artizani</i> pentru a împărți munca.",
        helpHow2: "<b>Verifică Banca:</b> Introdu inventarul în <i>Inventar Bancă</i>. <br><i>Sfat: Apasă <b>⚡ Calculează ce poți fabrica</b> pentru a-ți vedea limitele.</i>",
        helpHow3: "<b>La Cumpărături:</b> Verifică <i>Coșul de Piață</i>. Setează prețurile și apasă <b>🛒 Umple Tot</b> pentru a calcula bugetul de aur.",
        helpHow4: "<b>Trimite Comanda:</b> Revizuiește <i>Deficitul</i> și <i>Procesul de Fabricație</i>. Mergi la Setări > Integrări și copiază comanda pentru Discord."
    },

    pl: {
        tabPrefs: "Preferencje", tabInteg: "Integracje", tabData: "Dane", tabHelp: "Pomoc", resetDesc: "Wyczyść zapisany ekwipunek, koszyk i cele.",
        shareTitle: "Udostępnij / Importuj", shareDesc: "Wygeneruj kod, aby udostępnić swój bank, koszyk i cel, lub wklej kod kogoś innego, aby go załadować.",
        btnGenCode: "📤 Generuj i Kopiuj", btnLoadCode: "📥 Wczytaj Kod", importSuccess: "Konfiguracja wczytana pomyślnie!", importError: "Podano nieprawidłowy kod.", exportSuccess: "Kod skopiowany do schowka!",
        themeToggle: "☀️ / 🌙 Tryb Dzień/Noc", format: "Format Wyświetlania", optUnits: "Jednostki", optStacks: "Stosy (10k)", webhook: "Discord Webhook URL",
        prodCmd: "Dowództwo Produkcji", targetMetalLabel: "Metal Docelowy", boSource: "Strategia Wydobycia", optAttractor: "Wydajne (Szlifierki)", optCrusher: "Maks. Uzysk (Kruszarki)", crafters: "Rzemieślnicy", target: "Ilość", 
        btnMaxText: "⚡ Oblicz możliwe do wytworzenia",
        yieldMods: "Modyfikatory", mastery: "Mistrzostwo (+6%)", refining: "Rafinacja (+3%)", extraction: "Wydobycie (+3%)",
        btnDiscord: "📋 Kopiuj do Schowka", btnSend: "🚀 Wyślij do Discord",
        invBank: "Bank Ekwipunku", showAllBank: "Pokaż Wszystko", btnReset: "🧹 Resetuj Wszystko", defGather: "Deficyt do Zebrania", mfgPipe: "Linia Produkcyjna", marketCart: "Koszyk", btnAutoFill: "🛒 Wypełnij Wszystko",
        tblPrice: "Cena/10k", tblBuy: "Ilość do Kupienia", tblCost: "Koszt (z)", tblStash: "Bank + Zakup", cartTotal: "Suma Koszyka:",
        noTarget: "Brak celu.", allCovered: "✅ Wszystko zabezpieczone!",
        stepYields: "daje", stepExtract: "Ekstrahuj", stepAnd: "i", perCrafter: "(Na Rzemieślnika)", stepPrefix: "Krok",
        resetPrompt: "Zresetować wszystkie wartości do zera?", discHeader: "⚔️ ZAMÓWIENIE LOGISTYCZNE", discReq: "WYMAGANE ZBIERANIE:", discStock: "Zbiory zabezpieczone.", discCopied: "Skopiowano!",
        discMarket: "ZAKUPY NA RYNKU:", errWebhook: "Nieprawidłowy adres URL Webhook.", errSend: "Błąd wysyłania.", sucSend: "Zamówienie wysłane!",
        qAdd: "+10k", qAddStk: "+1 Stos", byproductsTitle: "ODZYSKANE PRODUKTY UBOCZNE",
        categories: { raw: "Surowce", basicExt: "Podstawowe Ekstrakcje", intOre: "Średnie Rudy", advOre: "Zaawansowane Rudy", catalyst: "Katalizatory", refined: "Rafinowane Metale" },
        items: { ...baseItems, water: "Woda", coal: "Węgiel", coke: "Koks", steel: "Stal", pi: "Surówka" },
        helpSubtitle: "Ostateczny kalkulator rzemieślniczy i panel logistyczny dla MO2.",
        helpFeatures: "🌟 Przegląd Funkcji",
        helpFeat1: "<b>Inteligencja Linii:</b> Automatycznie planuje kroki ekstrakcji i wytapiania. Pomija kroki, jeśli masz już półprodukty w banku.",
        helpFeat2: "<b>Oblicz Możliwe:</b> Skanuje ekwipunek, aby obliczyć absolutne maksimum docelowego metalu, które możesz wyprodukować.",
        helpFeat3: "<b>Inteligentny Koszyk:</b> Wprowadź ceny rynkowe. Użyj <i>Wypełnij Wszystko</i>, aby obliczyć dokładnie, ile złota potrzebujesz.",
        helpFeat4: "<b>Udostępnij / Importuj:</b> Wygeneruj kod swojej konfiguracji, aby błyskawicznie podzielić się nią z gildią.",
        helpFeat5: "<b>Wysyłanie na Discord:</b> Generuje pięknie sformatowane zamówienie robocze w Markdown—oddzielając zakupy od ręcznego zbierania.",
        helpHowTo: "📖 Jak Używać",
        helpHow1: "<b>Ustaw Cel:</b> Wybierz <i>Metal Docelowy</i> i <i>Ilość</i>. Ustaw liczbę <i>Rzemieślników</i>, aby podzielić pracę.",
        helpHow2: "<b>Sprawdź Bank:</b> Wprowadź swój ekwipunek do <i>Banku</i>. <br><i>Wskazówka: Kliknij <b>⚡ Oblicz możliwe do wytworzenia</b>, aby zobaczyć swoje limity.</i>",
        helpHow3: "<b>Zakupy:</b> Sprawdź moduł <i>Koszyka</i>. Ustaw ceny lokalne i kliknij <b>🛒 Wypełnij Wszystko</b>, aby obliczyć deficyt i budżet.",
        helpHow4: "<b>Wyślij Zamówienie:</b> Przejrzyj <i>Deficyt</i> i <i>Linię Produkcyjną</i>. Przejdź do Ustawień i skopiuj zamówienie na Discorda."
    },

    pt: {
        tabPrefs: "Preferências", tabInteg: "Integrações", tabData: "Dados", tabHelp: "Ajuda", resetDesc: "Limpe todo o seu inventário, quantidades do carrinho e alvos.",
        shareTitle: "Compartilhar / Importar", shareDesc: "Gere um código para compartilhar seu banco, carrinho e alvo com outros, ou cole um código para carregar o deles.",
        btnGenCode: "📤 Gerar e Copiar", btnLoadCode: "📥 Carregar Código", importSuccess: "Configuração carregada com sucesso!", importError: "Código fornecido inválido.", exportSuccess: "Código copiado!",
        themeToggle: "☀️ / 🌙 Modo Dia/Noite", format: "Formato de Exibição", optUnits: "Unidades", optStacks: "Pilhas (10k)", webhook: "URL Webhook Discord",
        prodCmd: "Comando de Produção", targetMetalLabel: "Metal Alvo", boSource: "Estratégia", optAttractor: "Eficiente (Moedores)", optCrusher: "Rendimento Max (Trituradores)", crafters: "Artesãos", target: "Quantidade", 
        btnMaxText: "⚡ Calcular fabricável",
        yieldMods: "Modificadores", mastery: "Maestria (+6%)", refining: "Refinamento (+3%)", extraction: "Extração (+3%)",
        btnDiscord: "📋 Copiar para Área de Transferência", btnSend: "🚀 Enviar para Discord",
        invBank: "Banco de Inventário", showAllBank: "Mostrar Tudo", btnReset: "🧹 Redefinir Tudo", defGather: "Déficit para Coletar", mfgPipe: "Linha de Fabricação", marketCart: "Carrinho", btnAutoFill: "🛒 Preencher Tudo",
        tblPrice: "Preço/10k", tblBuy: "Qtd para Comprar", tblCost: "Custo (o)", tblStash: "Banco + Compra", cartTotal: "Total do Carrinho:",
        noTarget: "Sem alvo.", allCovered: "✅ Tudo coberto!",
        stepYields: "rende", stepExtract: "Extrair", stepAnd: "e", perCrafter: "(Por Artesão)", stepPrefix: "Passo",
        resetPrompt: "Zerar todos os valores?", discHeader: "⚔️ ORDEM LOGÍSTICA", discReq: "COLETA MANUAL NECESSÁRIA:", discStock: "Coleta coberta.", discCopied: "Copiado!",
        discMarket: "COMPRAS NO MERCADO:", errWebhook: "URL Webhook inválida.", errSend: "Falha ao enviar.", sucSend: "Ordem enviada!",
        qAdd: "+10k", qAddStk: "+1 Pilha", byproductsTitle: "SUBPRODUTOS RECUPERADOS",
        categories: { raw: "Matérias-Primas", basicExt: "Extrações Básicas", intOre: "Minérios Intermediários", advOre: "Minérios Avançados", catalyst: "Catalisadores", refined: "Metais Refinados" },
        items: { ...baseItems, water: "Água", coal: "Carvão", coke: "Coque", steel: "Aço", pi: "Ferro-gusa" },
        helpSubtitle: "A calculadora definitiva de fabricação e painel logístico para MO2.",
        helpFeatures: "🌟 Visão Geral dos Recursos",
        helpFeat1: "<b>Inteligência de Pipeline:</b> Mapeia automaticamente tarefas de extração e fusão. Pula passos se você já tiver materiais intermediários no banco.",
        helpFeat2: "<b>Calcular Fabricável:</b> Escaneia seu inventário bancário para calcular a quantidade máxima absoluta do metal alvo que você pode produzir.",
        helpFeat3: "<b>Carrinho Inteligente:</b> Insira preços de mercado. Use <i>Preencher Tudo</i> para calcular exatamente quanto ouro você precisará.",
        helpFeat4: "<b>Compartilhar / Importar:</b> Gere um código Base64 de sua configuração para compartilhar instantaneamente com seus companheiros de guilda.",
        helpFeat5: "<b>Envio para Discord:</b> Gera uma ordem de serviço em Markdown—separando Compras de Mercado de Coleta Manual—pronta para o Discord.",
        helpHowTo: "📖 Como Usar",
        helpHow1: "<b>Defina seu Objetivo:</b> Selecione seu <i>Metal Alvo</i> e a <i>Quantidade</i>. Defina a contagem de <i>Artesãos</i> para dividir o trabalho.",
        helpHow2: "<b>Verifique seu Banco:</b> Insira seu inventário no <i>Banco de Inventário</i>. <br><i>Dica: Clique em <b>⚡ Calcular fabricável</b> para ver seus limites.</i>",
        helpHow3: "<b>Faça Compras:</b> Verifique o <i>Carrinho de Mercado</i>. Defina preços locais e clique em <b>🛒 Preencher Tudo</b> para calcular seu déficit.",
        helpHow4: "<b>Despache a Ordem:</b> Revise o <i>Déficit</i> e a <i>Linha de Fabricação</i>. Vá para Configurações > Integrações e copie a ordem para o Discord."
    },

    ru: {
        tabPrefs: "Настройки", tabInteg: "Интеграции", tabData: "Данные", tabHelp: "Справка", resetDesc: "Очистите инвентарь банка, корзину и цели.",
        shareTitle: "Поделиться / Импорт", shareDesc: "Сгенерируйте код, чтобы поделиться своим банком, корзиной и целями, или вставьте чужой код для загрузки.",
        btnGenCode: "📤 Сгенерировать и Копировать", btnLoadCode: "📥 Загрузить Код", importSuccess: "Настройки успешно загружены!", importError: "Неверный код.", exportSuccess: "Код скопирован в буфер!",
        themeToggle: "☀️ / 🌙 День/Ночь", format: "Формат", optUnits: "Единицы", optStacks: "Стаки (10k)", webhook: "Discord Webhook URL",
        prodCmd: "Производство", targetMetalLabel: "Целевой металл", boSource: "Стратегия", optAttractor: "Эффективность", optCrusher: "Макс. Выход", crafters: "Ремесленники", target: "Количество", 
        btnMaxText: "⚡ Рассчитать доступное",
        yieldMods: "Модификаторы", mastery: "Мастерство (+6%)", refining: "Переработка (+3%)", extraction: "Добыча (+3%)",
        btnDiscord: "📋 Скопировать", btnSend: "🚀 Отправить в Discord",
        invBank: "Банк", showAllBank: "Показать Все", btnReset: "🧹 Сбросить Все", defGather: "Осталось собрать", mfgPipe: "Процесс крафта", marketCart: "Корзина рынка", btnAutoFill: "🛒 Заполнить всё",
        tblPrice: "Цена/10k", tblBuy: "Купить", tblCost: "Стоимость", tblStash: "Банк + Покупка", cartTotal: "Итог корзины:",
        noTarget: "Цель не задана.", allCovered: "✅ Всё обеспечено!",
        stepYields: "дает", stepExtract: "Извлечь", stepAnd: "и", perCrafter: "(На крафтера)", stepPrefix: "Шаг",
        resetPrompt: "Сбросить все значения до нуля?", discHeader: "⚔️ ЛОГИСТИЧЕСКИЙ ЗАКАЗ", discReq: "ТРЕБУЕТСЯ СБОР:", discStock: "Сбор обеспечен.", discCopied: "Скопировано!",
        discMarket: "ПОКУПКИ НА РЫНКЕ:", errWebhook: "Неверный Webhook URL.", errSend: "Ошибка отправки.", sucSend: "Заказ отправлен!",
        qAdd: "+10k", qAddStk: "+1 Стак", byproductsTitle: "ПОБОЧНЫЕ ПРОДУКТЫ",
        categories: { raw: "Сырье", basicExt: "Базовые экстракции", intOre: "Средняя руда", advOre: "Продвинутая руда", catalyst: "Катализаторы", refined: "Очищенные металлы" },
        items: { ...baseItems, water: "Вода", coal: "Уголь", coke: "Кокс", steel: "Сталь", pi: "Чугун" },
        helpSubtitle: "Идеальный калькулятор крафта и логистическая панель для MO2.",
        helpFeatures: "🌟 Обзор функций",
        helpFeat1: "<b>Интеллект конвейера:</b> Автоматически планирует шаги добычи и переработки. Пропускает шаги, если промежуточные материалы уже есть в банке.",
        helpFeat2: "<b>Рассчитать доступное:</b> Сканирует инвентарь банка для расчета абсолютного максимума целевого металла, который вы можете произвести.",
        helpFeat3: "<b>Умная корзина:</b> Введите рыночные цены. Используйте <i>Заполнить всё</i>, чтобы рассчитать точный бюджет в золоте.",
        helpFeat4: "<b>Поделиться / Импорт:</b> Сгенерируйте код вашей конфигурации, чтобы мгновенно поделиться им с согильдийцами.",
        helpFeat5: "<b>Отправка в Discord:</b> Генерирует красиво отформатированный заказ Markdown — разделяя покупки на рынке и ручной сбор.",
        helpHowTo: "📖 Как использовать",
        helpHow1: "<b>Постановка цели:</b> Выберите <i>Целевой металл</i> и <i>Количество</i>. Задайте количество <i>Ремесленников</i> для разделения работы.",
        helpHow2: "<b>Проверка банка:</b> Введите свой инвентарь в <i>Банк</i>. <br><i>Подсказка: Нажмите <b>⚡ Рассчитать доступное</b>, чтобы узнать свои пределы.</i>",
        helpHow3: "<b>Покупки:</b> Проверьте <i>Корзину рынка</i>. Задайте локальные цены и нажмите <b>🛒 Заполнить всё</b> для расчета дефицита и золота.",
        helpHow4: "<b>Отправка заказа:</b> Проверьте <i>Дефицит для сбора</i> и <i>Процесс крафта</i>. Скопируйте заказ в настройках для отправки в Discord."
    },

    fi: {
        tabPrefs: "Asetukset", tabInteg: "Integraatiot", tabData: "Tiedot", tabHelp: "Ohje", resetDesc: "Tyhjennä pankin varasto, ostoskori ja tavoitteet.",
        shareTitle: "Jaa / Tuo Asetukset", shareDesc: "Luo koodi jakaaksesi pankkisi, ostoskorisi ja tavoitteesi, tai liitä koodi ladataksesi muiden asetukset.",
        btnGenCode: "📤 Luo ja Kopioi", btnLoadCode: "📥 Lataa Koodi", importSuccess: "Asetukset ladattu onnistuneesti!", importError: "Virheellinen koodi.", exportSuccess: "Koodi kopioitu leikepöydälle!",
        themeToggle: "☀️ / 🌙 Päivä/Yö", format: "Muoto", optUnits: "Yksiköt", optStacks: "Pinot (10k)", webhook: "Discord Webhook URL",
        prodCmd: "Tuotantokomento", targetMetalLabel: "Kohdemetalli", boSource: "Strategia", optAttractor: "Tehokas", optCrusher: "Maks. Tuotto", crafters: "Käsityöläiset", target: "Määrä", 
        btnMaxText: "⚡ Laske valmistettavissa oleva",
        yieldMods: "Muuttujat", mastery: "Mestaruus (+6%)", refining: "Jalostus (+3%)", extraction: "Louhinta (+3%)",
        btnDiscord: "📋 Kopioi Leikepöydälle", btnSend: "🚀 Lähetä Discordiin",
        invBank: "Pankkivarasto", showAllBank: "Näytä Kaikki", btnReset: "🧹 Nollaa Kaikki", defGather: "Kerättävä Vaje", mfgPipe: "Tuotantolinja", marketCart: "Ostoskori", btnAutoFill: "🛒 Täytä Kaikki",
        tblPrice: "Hinta/10k", tblBuy: "Ostomäärä", tblCost: "Kustannus (k)", tblStash: "Pankki + Osto", cartTotal: "Korin Yhteensä:",
        noTarget: "Ei tavoitetta.", allCovered: "✅ Kaikki katettu!",
        stepYields: "tuottaa", stepExtract: "Erota", stepAnd: "ja", perCrafter: "(Per Tekijä)", stepPrefix: "Vaihe",
        resetPrompt: "Nollaa kaikki arvot nollaan?", discHeader: "⚔️ LOGISTIIKKATILAUS", discReq: "MANUAALINEN KERÄYS:", discStock: "Kaikki keräys katettu.", discCopied: "Kopioitu!",
        discMarket: "MARKKINAOSTOT:", errWebhook: "Virheellinen Webhook URL.", errSend: "Lähetys epäonnistui.", sucSend: "Tilaus lähetetty!",
        qAdd: "+10k", qAddStk: "+1 Pino", byproductsTitle: "TALTEENOTETUT SIVUTUOTTEET",
        categories: { raw: "Raaka-aineet", basicExt: "Peruserottelut", intOre: "Keskivahvat Malmit", advOre: "Kehittyneet Malmit", catalyst: "Katalyytit", refined: "Jalostetut Metallit" },
        items: { ...baseItems, water: "Vesi", coal: "Hiili", coke: "Koksi", steel: "Teräs", pi: "Harkkorauta" },
        helpSubtitle: "Lopullinen MO2 tuotantolaskin ja logistiikkapaneeli.",
        helpFeatures: "🌟 Ominaisuudet",
        helpFeat1: "<b>Tuotantolinjan Äly:</b> Suunnittelee automaattisesti erottelu- ja sulatusvaiheet. Ohittaa vaiheet, jos sinulla on jo välimateriaaleja pankissa.",
        helpFeat2: "<b>Laske Valmistettavissa oleva:</b> Skannaa pankkisi laskeakseen absoluuttisen enimmäismäärän kohdemetallia, jonka voit valmistaa.",
        helpFeat3: "<b>Älykäs Ostoskori:</b> Syötä markkinahinnat. Käytä <i>Täytä Kaikki</i> laskeaksesi tarkan kullan tarpeen.",
        helpFeat4: "<b>Jaa / Tuo:</b> Luo Base64-koodi asetuksistasi jakaaksesi ne välittömästi killan jäsenten kanssa.",
        helpFeat5: "<b>Discord-Lähetys:</b> Luo kauniisti muotoillun Markdown-työtilauksen—erottaen markkinaostot ja keräyksen—valmiina Discordiin.",
        helpHowTo: "📖 Käyttöohje",
        helpHow1: "<b>Aseta Tavoite:</b> Valitse <i>Kohdemetalli</i> ja <i>Määrä</i>. Aseta <i>Käsityöläisten</i> määrä jakaaksesi työtaakan.",
        helpHow2: "<b>Tarkista Pankki:</b> Syötä varastosi <i>Pankkivarastoon</i>. <br><i>Vinkki: Klikkaa <b>⚡ Laske valmistettavissa oleva</b> nähdäksesi rajasi.</i>",
        helpHow3: "<b>Ostoksille:</b> Tarkista <i>Ostoskori</i>. Aseta paikalliset hinnat ja klikkaa <b>🛒 Täytä Kaikki</b> laskeaksesi vajeen.",
        helpHow4: "<b>Lähetä Tilaus:</b> Tarkista <i>Kerättävä Vaje</i> ja <i>Tuotantolinja</i>. Kopioi tilaus Asetuksista Discordia varten."
    },

    hu: {
        tabPrefs: "Beállítások", tabInteg: "Integrációk", tabData: "Adatok", tabHelp: "Súgó", resetDesc: "Törölje a mentett banki készletet, a kosarat és a célokat.",
        shareTitle: "Megosztás / Importálás", shareDesc: "Generálj kódot a bankod, kosarad és célod megosztásához, vagy illessz be egy kódot a betöltéshez.",
        btnGenCode: "📤 Generálás & Másolás", btnLoadCode: "📥 Kód Betöltése", importSuccess: "Beállítás sikeresen betöltve!", importError: "Érvénytelen kód.", exportSuccess: "Kód a vágólapra másolva!",
        themeToggle: "☀️ / 🌙 Nappali/Éjszakai Mód", format: "Kijelző Formátum", optUnits: "Egységek", optStacks: "Halmok (10k)", webhook: "Discord Webhook URL",
        prodCmd: "Gyártási Parancsnokság", targetMetalLabel: "Cél Fém", boSource: "Kivonási Stratégia", optAttractor: "Hatékony", optCrusher: "Max Hozam", crafters: "Kézművesek", target: "Mennyiség", 
        btnMaxText: "⚡ Készíthető mennyiség",
        yieldMods: "Hozam Módosítók", mastery: "Mesterfok (+6%)", refining: "Finomítás (+3%)", extraction: "Kivonás (+3%)",
        btnDiscord: "📋 Másolás Vágólapra", btnSend: "🚀 Küldés Discordra",
        invBank: "Bankkészlet", showAllBank: "Összes Mutatása", btnReset: "🧹 Összes Visszaállítása", defGather: "Összegyűjtendő Hiány", mfgPipe: "Gyártási Folyamat", marketCart: "Piaci Kosár", btnAutoFill: "🛒 Összes Kitöltése",
        tblPrice: "Ár/10k", tblBuy: "Vásárolandó Mennyiség", tblCost: "Költség (a)", tblStash: "Bank + Vásárlás", cartTotal: "Kosár Összesen:",
        noTarget: "Nincs cél beállítva.", allCovered: "✅ Minden biztosítva!",
        stepYields: "hozama", stepExtract: "Kivonás", stepAnd: "és", perCrafter: "(Kézművesenként)", stepPrefix: "Lépés",
        resetPrompt: "Minden érték lenullázása?", discHeader: "⚔️ LOGISZTIKAI RENDELÉS", discReq: "KÉZI GYŰJTÉS SZÜKSÉGES:", discStock: "Minden gyűjtés lefedve.", discCopied: "Másolva!",
        discMarket: "PIACI VÁSÁRLÁSOK:", errWebhook: "Érvénytelen Webhook URL.", errSend: "Küldés sikertelen.", sucSend: "Rendelés elküldve!",
        qAdd: "+10k", qAddStk: "+1 Halom", byproductsTitle: "VISSZANYERT MELLÉKTERMÉKEK",
        categories: { raw: "Nyersanyagok", basicExt: "Alap Kivonások", intOre: "Köztes Ércek", advOre: "Fejlett Ércek", catalyst: "Katalizátorok", refined: "Finomított Fémek" },
        items: { ...baseItems, water: "Víz", coal: "Szén", coke: "Koksz", steel: "Acél", pi: "Nyersvas" },
        helpSubtitle: "A végső MO2 gyártási kalkulátor és logisztikai műszerfal.",
        helpFeatures: "🌟 Funkciók Áttekintése",
        helpFeat1: "<b>Folyamat Intelligencia:</b> Automatikusan feltérképezi a kivonási és olvasztási lépéseket. Kihagyja a lépéseket, ha már vannak köztes anyagaid a bankban.",
        helpFeat2: "<b>Készíthető Mennyiség:</b> Beszkenneli a banki készletedet, hogy kiszámítsa a célfém maximális mennyiségét, amit az aktuális anyagokból előállíthatsz.",
        helpFeat3: "<b>Okos Kosár:</b> Add meg a piaci árakat. Használd az <i>Összes Kitöltése</i> gombot a pontos aranyköltség kiszámításához.",
        helpFeat4: "<b>Megosztás / Importálás:</b> Generálj kódot a beállításaidról, hogy azonnal megoszthasd a céhtagokkal.",
        helpFeat5: "<b>Discord Küldés:</b> Gyönyörűen formázott Markdown munkaparancsot generál, elkülönítve a piaci vásárlásokat és a kézi gyűjtést.",
        helpHowTo: "📖 Használati Útmutató",
        helpHow1: "<b>Állítsd be a Célt:</b> Válaszd ki a <i>Cél Fémet</i> és a <i>Mennyiséget</i>. Állítsd be a <i>Kézművesek</i> számát a munka elosztásához.",
        helpHow2: "<b>Ellenőrizd a Bankot:</b> Írd be a készleted a <i>Bankkészletbe</i>. <br><i>Tipp: Kattints a <b>⚡ Készíthető mennyiség</b> gombra a limitek megtekintéséhez.</i>",
        helpHow3: "<b>Vásárlás:</b> Nézd meg a <i>Piaci Kosarat</i>. Állíts be árakat, majd kattints a <b>🛒 Összes Kitöltése</b> gombra.",
        helpHow4: "<b>Rendelés Küldése:</b> Nézd át a <i>Hiányt</i> és a <i>Gyártási Folyamatot</i>. Másold ki a rendelést a Beállításokban a Discordhoz."
    },

    tr: {
        tabPrefs: "Tercihler", tabInteg: "Entegrasyonlar", tabData: "Veriler", tabHelp: "Yardım", resetDesc: "Kayıtlı banka envanterini, sepet miktarlarını ve hedefleri temizle.",
        shareTitle: "Kurulumu Paylaş / İçe Aktar", shareDesc: "Bankanızı, sepetinizi ve hedefinizi paylaşmak için bir kod oluşturun veya kod yükleyin.",
        btnGenCode: "📤 Oluştur ve Kopyala", btnLoadCode: "📥 Kodu Yükle", importSuccess: "Kurulum başarıyla yüklendi!", importError: "Geçersiz kod.", exportSuccess: "Kod panoya kopyalandı!",
        themeToggle: "☀️ / 🌙 Gündüz/Gece Modu", format: "Görünüm Formatı", optUnits: "Birimler", optStacks: "Yığınlar (10k)", webhook: "Discord Webhook URL",
        prodCmd: "Üretim Komutu", targetMetalLabel: "Hedef Metal", boSource: "Çıkarma Stratejisi", optAttractor: "Verimli", optCrusher: "Maks. Verim", crafters: "Zanaatkarlar", target: "Miktar", 
        btnMaxText: "⚡ Üretilebilir olanı hesapla",
        yieldMods: "Verim Çarpanları", mastery: "Ustalık (+6%)", refining: "Arıtma (+3%)", extraction: "Çıkarma (+3%)",
        btnDiscord: "📋 Panoya Kopyala", btnSend: "🚀 Discord'a Gönder",
        invBank: "Banka Envanteri", showAllBank: "Hepsini Göster", btnReset: "🧹 Her Şeyi Sıfırla", defGather: "Toplanacak Eksik", mfgPipe: "Üretim Hattı", marketCart: "Market Sepeti", btnAutoFill: "🛒 Tümünü Doldur",
        tblPrice: "Fiyat/10k", tblBuy: "Alınacak Miktar", tblCost: "Maliyet (a)", tblStash: "Banka + Alım", cartTotal: "Sepet Toplamı:",
        noTarget: "Hedef yok.", allCovered: "✅ Her şey güvence altında!",
        stepYields: "verir", stepExtract: "Çıkar", stepAnd: "ve", perCrafter: "(Zanaatkar Başına)", stepPrefix: "Adım",
        resetPrompt: "Tüm değerler sıfırlansın mı?", discHeader: "⚔️ LOJİSTİK SİPARİŞİ", discReq: "MANUEL TOPLAMA GEREKLİ:", discStock: "Tüm toplama tamamlandı.", discCopied: "Kopyalandı!",
        discMarket: "MARKET ALIMLARI:", errWebhook: "Geçersiz Webhook URL.", errSend: "Gönderim başarısız.", sucSend: "Sipariş gönderildi!",
        qAdd: "+10k", qAddStk: "+1 Yığın", byproductsTitle: "KURTARILAN YAN ÜRÜNLER",
        categories: { raw: "Hammadde", basicExt: "Temel Çıkarımlar", intOre: "Orta Seviye Cevherler", advOre: "Gelişmiş Cevherler", catalyst: "Katalizörler", refined: "Arıtılmış Metaller" },
        items: { ...baseItems, water: "Su", coal: "Kömür", coke: "Kok", steel: "Çelik", pi: "Pik Demir" },
        helpSubtitle: "Nihai MO2 üretim hesaplayıcısı ve lojistik panosu.",
        helpFeatures: "🌟 Özelliklere Genel Bakış",
        helpFeat1: "<b>Üretim Hattı Zekası:</b> Çıkarma ve eritme adımlarını otomatik planlar. Bankada halihazırda ara malzemeleriniz varsa adımları atlar.",
        helpFeat2: "<b>Üretilebilir Olanı Hesapla:</b> Elinizdekilerle üretebileceğiniz mutlak maksimum hedef metal miktarını hesaplamak için bankanızı tarar.",
        helpFeat3: "<b>Akıllı Sepet:</b> Market fiyatlarını girin. Altın maliyetini hesaplamak için <i>Tümünü Doldur</i> seçeneğini kullanın.",
        helpFeat4: "<b>Paylaş / İçe Aktar:</b> Lonca üyeleriyle anında paylaşmak için kurulumunuzun bir Base64 kodunu oluşturun.",
        helpFeat5: "<b>Discord Gönderimi:</b> Market Alımlarını ve Manuel Toplamayı ayıran—Discord için hazır bir Markdown iş emri oluşturur.",
        helpHowTo: "📖 Nasıl Kullanılır",
        helpHow1: "<b>Hedefinizi Belirleyin:</b> <i>Hedef Metalinizi</i> ve <i>Miktarı</i> seçin. İş yükünü bölmek için <i>Zanaatkar</i> sayısını ayarlayın.",
        helpHow2: "<b>Bankanızı Kontrol Edin:</b> Envanterinizi <i>Banka Envanterine</i> girin. <br><i>İpucu: Sınırlarınızı görmek için <b>⚡ Üretilebilir olanı hesapla</b> butonuna tıklayın.</i>",
        helpHow3: "<b>Alışverişe Çıkın:</b> <i>Market Sepetini</i> kontrol edin. Fiyatları belirleyin ve açığı hesaplamak için <b>🛒 Tümünü Doldur</b> butonuna tıklayın.",
        helpHow4: "<b>Siparişi Gönderin:</b> <i>Toplanacak Eksik</i> ve <i>Üretim Hattını</i> gözden geçirin. Ayarlara gidin ve Discord için siparişi kopyalayın."
    },

    sv: {
        tabPrefs: "Inställningar", tabInteg: "Integrationer", tabData: "Data", tabHelp: "Hjälp", resetDesc: "Rensa sparat bankinventarie, varukorg och mål.",
        shareTitle: "Dela / Importera", shareDesc: "Generera en kod för att dela din bank, varukorg och mål, eller klistra in en kod för att ladda andras.",
        btnGenCode: "📤 Generera & Kopiera", btnLoadCode: "📥 Ladda Kod", importSuccess: "Inställningar laddades framgångsrikt!", importError: "Ogiltig kod.", exportSuccess: "Kod kopierad!",
        themeToggle: "☀️ / 🌙 Dag/Nattläge", format: "Visningsformat", optUnits: "Enheter", optStacks: "Travar (10k)", webhook: "Discord Webhook URL",
        prodCmd: "Produktionskommando", targetMetalLabel: "Målmetall", boSource: "Extraktionsstrategi", optAttractor: "Effektiv (Kvarnar)", optCrusher: "Max Utbyte (Krossar)", crafters: "Hantverkare", target: "Mängd", 
        btnMaxText: "⚡ Beräkna tillverkningsbart",
        yieldMods: "Utbytesmodifierare", mastery: "Mästerskap (+6%)", refining: "Raffinering (+3%)", extraction: "Extraktion (+3%)",
        btnDiscord: "📋 Kopiera till Urklipp", btnSend: "🚀 Skicka till Discord",
        invBank: "Bankinventarie", showAllBank: "Visa Allt", btnReset: "🧹 Återställ Allt", defGather: "Underskott att Samla", mfgPipe: "Tillverkningsprocess", marketCart: "Varukorg", btnAutoFill: "🛒 Fyll i Allt",
        tblPrice: "Pris/10k", tblBuy: "Mängd att Köpa", tblCost: "Kostnad (g)", tblStash: "Bank + Köp", cartTotal: "Varukorg Totalt:",
        noTarget: "Inget mål satt.", allCovered: "✅ Allt täckt!",
        stepYields: "ger", stepExtract: "Extrahera", stepAnd: "och", perCrafter: "(Per Hantverkare)", stepPrefix: "Steg",
        resetPrompt: "Återställ alla värden till noll?", discHeader: "⚔️ LOGISTIKORDER", discReq: "MANUELL INSAMLING KRÄVS:", discStock: "All insamling täckt.", discCopied: "Kopierat!",
        discMarket: "MARKNADSKÖP:", errWebhook: "Ogiltig Webhook URL.", errSend: "Kunde inte skicka.", sucSend: "Order skickad!",
        qAdd: "+10k", qAddStk: "+1 Trave", byproductsTitle: "ÅTERVUNNA BIPRODUKTER",
        categories: { raw: "Råmaterial", basicExt: "Grundläggande Extraktioner", intOre: "Mellanmalmer", advOre: "Avancerade Malmer", catalyst: "Katalysatorer", refined: "Raffinerade Metaller" },
        items: { ...baseItems, water: "Vatten", coal: "Kol", coke: "Koks", steel: "Stål", pi: "Tackjärn" },
        helpSubtitle: "Den ultimata MO2-tillverkningskalkylatorn och logistikpanelen.",
        helpFeatures: "🌟 Funktionsöversikt",
        helpFeat1: "<b>Processintelligens:</b> Kartlägger automatiskt extraktions- och smältsteg. Hoppar över steg om du redan har mellanmaterial i banken.",
        helpFeat2: "<b>Beräkna Tillverkningsbart:</b> Skannar ditt bankinventarie för att beräkna den absoluta maxmängden av målmetallen du kan producera.",
        helpFeat3: "<b>Smart Varukorg:</b> Ange marknadspriser. Använd <i>Fyll i Allt</i> för att exakt beräkna din guldkostnad.",
        helpFeat4: "<b>Dela / Importera:</b> Generera en kod för att omedelbart dela din inställning med dina gillesmedlemmar.",
        helpFeat5: "<b>Discord-Utskick:</b> Genererar en snyggt formaterad arbetsorder—som separerar marknadsköp från insamling—redo för Discord.",
        helpHowTo: "📖 Hur man använder",
        helpHow1: "<b>Sätt ditt Mål:</b> Välj din <i>Målmetall</i> och <i>Mängd</i>. Ställ in antalet <i>Hantverkare</i> för att dela på arbetsbördan.",
        helpHow2: "<b>Kolla din Bank:</b> Skriv in ditt inventarie i <i>Bankinventariet</i>. <br><i>Tips: Klicka på <b>⚡ Beräkna tillverkningsbart</b> för att se dina gränser.</i>",
        helpHow3: "<b>Handla:</b> Kolla <i>Varukorgen</i>. Sätt lokala priser och klicka på <b>🛒 Fyll i Allt</b> för att beräkna underskott och budget.",
        helpHow4: "<b>Skicka Ordern:</b> Granska <i>Underskott</i> och <i>Process</i>. Gå till Inställningar > Integrationer och kopiera ordern för Discord."
    },

    cs: {
        tabPrefs: "Předvolby", tabInteg: "Integrace", tabData: "Data", tabHelp: "Nápověda", resetDesc: "Vymazat uložený inventář, košík a cíle.",
        shareTitle: "Sdílet / Importovat", shareDesc: "Vygenerujte kód pro sdílení vaší banky, košíku a cíle, nebo vložte kód pro načtení jiných.",
        btnGenCode: "📤 Generovat & Kopírovat", btnLoadCode: "📥 Načíst Kód", importSuccess: "Nastavení úspěšně načteno!", importError: "Neplatný kód.", exportSuccess: "Kód zkopírován!",
        themeToggle: "☀️ / 🌙 Den/Noc Režim", format: "Formát Zobrazení", optUnits: "Jednotky", optStacks: "Svazky (10k)", webhook: "Discord Webhook URL",
        prodCmd: "Výrobní Velitelství", targetMetalLabel: "Cílový Kov", boSource: "Strategie", optAttractor: "Efektivní", optCrusher: "Max. Výtěžek", crafters: "Řemeslníci", target: "Množství", 
        btnMaxText: "⚡ Vypočítat vyrobitelné",
        yieldMods: "Modifikátory Výtěžku", mastery: "Mistrovství (+6%)", refining: "Rafinace (+3%)", extraction: "Těžba (+3%)",
        btnDiscord: "📋 Kopírovat do Schránky", btnSend: "🚀 Odeslat na Discord",
        invBank: "Banka Inventáře", showAllBank: "Zobrazit Vše", btnReset: "🧹 Resetovat Vše", defGather: "Deficit k Těžbě", mfgPipe: "Výrobní Proces", marketCart: "Nákupní Košík", btnAutoFill: "🛒 Vyplnit Vše",
        tblPrice: "Cena/10k", tblBuy: "Množství k Nákupu", tblCost: "Cena (z)", tblStash: "Banka + Nákup", cartTotal: "Košík Celkem:",
        noTarget: "Žádný cíl.", allCovered: "✅ Vše zajištěno!",
        stepYields: "dává", stepExtract: "Vytěžit", stepAnd: "a", perCrafter: "(Na Řemeslníka)", stepPrefix: "Krok",
        resetPrompt: "Vynulovat všechny hodnoty?", discHeader: "⚔️ LOGISTICKÁ OBJEDNÁVKA", discReq: "RUČNÍ TĚŽBA:", discStock: "Těžba pokryta.", discCopied: "Zkopírováno!",
        discMarket: "NÁKUPY NA TRHU:", errWebhook: "Neplatná Webhook URL.", errSend: "Odeslání selhalo.", sucSend: "Objednávka odeslána!",
        qAdd: "+10k", qAddStk: "+1 Svazek", byproductsTitle: "ZÍSKANÉ VEDLEJŠÍ PRODUKTY",
        categories: { raw: "Suroviny", basicExt: "Základní Těžba", intOre: "Střední Rudy", advOre: "Pokročilé Rudy", catalyst: "Katalyzátory", refined: "Rafinované Kovy" },
        items: { ...baseItems, water: "Voda", coal: "Uhlí", coke: "Koks", steel: "Ocel", pi: "Surové železo" },
        helpSubtitle: "Ultimátní MO2 výrobní kalkulačka a logistický panel.",
        helpFeatures: "🌟 Přehled Funkcí",
        helpFeat1: "<b>Inteligence Výroby:</b> Automaticky mapuje kroky těžby a tavení. Přeskočí kroky, pokud už máte meziprodukty v bance.",
        helpFeat2: "<b>Vypočítat Vyrobitelné:</b> Prohledá inventář a vypočítá absolutní maximum cílového kovu, které můžete vyrobit.",
        helpFeat3: "<b>Chytrý Košík:</b> Zadejte tržní ceny. Použijte <i>Vyplnit Vše</i> k přesnému výpočtu potřebného zlata.",
        helpFeat4: "<b>Sdílet / Importovat:</b> Vygenerujte kód vašeho nastavení pro okamžité sdílení s členy gildy.",
        helpFeat5: "<b>Odeslání na Discord:</b> Generuje krásně formátovanou Markdown objednávku—oddělující Nákupy a Těžbu—připravenou pro Discord.",
        helpHowTo: "📖 Jak Používat",
        helpHow1: "<b>Nastavte Cíl:</b> Vyberte <i>Cílový Kov</i> a <i>Množství</i>. Nastavte počet <i>Řemeslníků</i> pro rozdělení práce.",
        helpHow2: "<b>Zkontrolujte Banku:</b> Zadejte inventář do <i>Banky</i>. <br><i>Tip: Klikněte na <b>⚡ Vypočítat vyrobitelné</b> pro zjištění vašich limitů.</i>",
        helpHow3: "<b>Jděte Nakupovat:</b> Zkontrolujte <i>Košík</i>. Nastavte ceny a klikněte na <b>🛒 Vyplnit Vše</b> pro výpočet deficitu.",
        helpHow4: "<b>Odešlete Objednávku:</b> Zkontrolujte <i>Deficit</i> a <i>Výrobní Proces</i>. Přejděte do Nastavení a zkopírujte objednávku pro Discord."
    },

    ar: {
        tabPrefs: "التفضيلات", tabInteg: "عمليات الدمج", tabData: "البيانات", tabHelp: "مساعدة", resetDesc: "امسح جميع مخزون البنك المحفوظ، وكميات عربة السوق، والأهداف.",
        shareTitle: "مشاركة / استيراد الإعداد", shareDesc: "قم بإنشاء كود لمشاركة بنكك وعربتك وهدفك مع الآخرين، أو الصق كوداً لتحميل إعداداتهم.",
        btnGenCode: "📤 إنشاء ونسخ", btnLoadCode: "📥 تحميل الكود", importSuccess: "تم تحميل الإعداد بنجاح!", importError: "كود غير صالح.", exportSuccess: "تم نسخ الكود!",
        themeToggle: "☀️ / 🌙 تبديل وضع النهار / الليل", format: "تنسيق العرض", optUnits: "الوحدات", optStacks: "المكدسات (10k)", webhook: "Discord Webhook URL",
        prodCmd: "أمر الإنتاج", targetMetalLabel: "المعدن المستهدف", boSource: "استراتيجية الاستخراج", optAttractor: "فعال (مطاحن)", optCrusher: "الحد الأقصى للعائد (كسارات)", crafters: "الحرفيون", target: "الكمية", 
        btnMaxText: "⚡ حساب ما يمكن صياغته من المخزون",
        yieldMods: "معدلات العائد", mastery: "الإتقان (+6%)", refining: "التكرير (+3%)", extraction: "الاستخراج (+3%)",
        btnDiscord: "📋 نسخ إلى الحافظة", btnSend: "🚀 إرسال الطلب إلى Discord",
        invBank: "بنك المخزون", showAllBank: "إظهار كل المواد", btnReset: "🧹 إعادة تعيين الكل", defGather: "العجز المراد جمعه يدوياً", mfgPipe: "خط أنابيب التصنيع", marketCart: "عربة السوق", btnAutoFill: "🛒 ملء الكل تلقائياً",
        tblPrice: "السعر / 10k", tblBuy: "الكمية للشراء", tblCost: "التكلفة (ذ)", tblStash: "البنك + الشراء", cartTotal: "إجمالي العربة:",
        noTarget: "لم يتم تحديد هدف.", allCovered: "✅ تم تغطية جميع المواد الخام!",
        stepYields: "ينتج", stepExtract: "استخراج", stepAnd: "و", perCrafter: "(لكل حرفي)", stepPrefix: "خطوة",
        resetPrompt: "إعادة تعيين جميع قيم البنك والعربة إلى الصفر؟", discHeader: "⚔️ طلب لوجستي", discReq: "التجميع اليدوي المطلوب:", discStock: "تمت تغطية جميع التجميعات.", discCopied: "تم النسخ!",
        discMarket: "مشتريات السوق:", errWebhook: "عنوان URL غير صالح لـ Discord Webhook.", errSend: "فشل الإرسال.", sucSend: "تم إرسال الطلب!",
        qAdd: "+10k", qAddStk: "+1 مكدس", byproductsTitle: "المنتجات الثانوية المستردة",
        categories: { raw: "المواد الخام", basicExt: "الاستخراجات الأساسية", intOre: "الخامات المتوسطة", advOre: "الخامات المتقدمة", catalyst: "المحفزات", refined: "المعادن المكررة" },
        items: { ...baseItems, water: "ماء", coal: "فحم", coke: "فحم الكوك", steel: "صلب", pi: "حديد غفل" },
        helpSubtitle: "أداة حساب التصنيع اللوجستية المثالية للعبة MO2.",
        helpFeatures: "🌟 نظرة عامة على الميزات",
        helpFeat1: "<b>ذكاء خط الإنتاج:</b> يخطط تلقائياً لخطوات الاستخراج والصهر. يتخطى الخطوات إذا كان لديك بالفعل مواد وسيطة في البنك.",
        helpFeat2: "<b>حساب ما يمكن صياغته:</b> يمسح مخزون البنك الخاص بك لحساب الحد الأقصى المطلق للمعدن المستهدف الذي يمكنك إنتاجه.",
        helpFeat3: "<b>عربة ذكية:</b> أدخل أسعار السوق. استخدم <i>ملء الكل</i> لحساب تكلفة الذهب بدقة.",
        helpFeat4: "<b>مشاركة / استيراد:</b> أنشئ كوداً لإعدادك لمشاركته على الفور مع أعضاء نقابتك.",
        helpFeat5: "<b>إرسال Discord:</b> يولد طلب عمل بتنسيق Markdown جميل—يفصل مشتريات السوق عن الجمع اليدوي—جاهز للـ Discord.",
        helpHowTo: "📖 كيفية الاستخدام",
        helpHow1: "<b>حدد هدفك:</b> اختر <i>المعدن المستهدف</i> و<i>الكمية</i>. عيّن عدد <i>الحرفيين</i> لتقسيم العمل.",
        helpHow2: "<b>تحقق من بنكك:</b> أدخل مخزونك في <i>بنك المخزون</i>. <br><i>نصيحة: انقر فوق <b>⚡ حساب ما يمكن صياغته من المخزون</b> لمعرفة حدودك.</i>",
        helpHow3: "<b>اذهب للتسوق:</b> تحقق من وحدة <i>عربة السوق</i>. حدد الأسعار وانقر على <b>🛒 ملء الكل تلقائياً</b> لحساب العجز.",
        helpHow4: "<b>أرسل الطلب:</b> راجع <i>العجز</i> و<i>خط أنابيب التصنيع</i>. اذهب إلى الإعدادات ثم الدمج وانسخ الطلب للـ Discord."
    }
};